---
- name: Check if Apache and PHP module for Apache is installed
  command: bash -c "dpkg --get-selections | grep {{ item }}"
  register: apache2_installed
  ignore_errors: True
  with_items:
    - apache2
    - libapache2-mod-php5
  tags:
    - apache_setup

- name: Install Apache and PHP module for Apache if uninstalled
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-php5
  when: apache2_installed|failed
  tags:
    - apache_setup