---
- name: Check if mysql-server is installed
  shell: dpkg --get-selections 2>&1 | grep mysql
  register: mysql_server_installed
  ignore_errors: true

- name: Install mysql-server if its uninstalled
  apt: name=mysql-server state=present force=yes
  when: mysql_server_installed|failed

- name: Check if php5-mysql is installed
  shell: dpkg --get-selections 2>&1 | grep php5-mysql
  register: php5_mysql_installed
  ignore_errors: true

- name: Install php5-mysql if its uninstalled
  apt: name=php5-mysql state=present force=yes
  when: php5_mysql_installed|failed