---
- name: Check if mysql-server and php5-mysql are installed
  command: service --status-all | grep {{ item }}
  register: mysql_installed
  ignore_errors: True
  with_items:
    - mysql-server
    - php5-mysql
  tags:
    - mysql_setup

- name: Install mysql-server and php5-mysql if uninstalled
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - php5-mysql
  when: mysql_installed|failed
  tags:
    - mysql_setup