---
- name: Check if php5 and php5-mcrypt are installed
  command: dpkg --get-selections | grep {{ item }}
  register: mysql_installed
  ignore_errors: True
  with_items:
    - php5
    - php5-mcrypt
  tags:
    - php_setup

- name: Install php5 and php5-mcrypt if uninstalled
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-mcrypt
  when: mysql_installed|failed
  tags:
    - php_setup